#pragma once

#define L2DE_TILEDMAP_SUPPORTED_VERSION "1.10"
#define L2DE_TILEDMAP_SUPPORTED_ORIENTATION "orthogonal"
#define L2DE_TILEDMAP_SUPPORTED_ENCODING "csv"

//Common
#define L2DE_TILEDMAP_ATTR_TILEWIDTH "tilewidth"
#define L2DE_TILEDMAP_ATTR_TILEHEIGHT "tileheight"
#define L2DE_TILEDMAP_ATTR_WIDTH "width"
#define L2DE_TILEDMAP_ATTR_HEIGHT "height"
#define L2DE_TILEDMAP_ATTR_NAME "name"

// Map
#define L2DE_TILEDMAP_NODE_MAP "map"
#define L2DE_TILEDMAP_ATTR_VERSION "version"
#define L2DE_TILEDMAP_ATTR_TILEDVERSION "tiledversion"
#define L2DE_TILEDMAP_ATTR_ORIENTATION "orientation"
#define L2DE_TILEDMAP_ATTR_INFINITE "infinite"
#define L2DE_TILEDMAP_ATTR_BACKGROUND_COLOR "backgroundcolor"

// Tileset
#define L2DE_TILEDMAP_NODE_TILESET "tileset"
#define L2DE_TILEDMAP_NODE_IMAGE "image"
#define L2DE_TILEDMAP_ATTR_FIRSTGID "firstgid"
#define L2DE_TILEDMAP_ATTR_SOURCE "source"
#define L2DE_TILEDMAP_ATTR_COLUMNS "columns"
#define L2DE_TILEDMAP_ATTR_TILECOUNT "tilecount"
#define L2DE_TILEDMAP_ATTR_SPACING "spacing"
#define L2DE_TILEDMAP_ATTR_MARGIN "margin"

// Layer
#define L2DE_TILEDMAP_NODE_LAYER "layer"
#define L2DE_TILEDMAP_NODE_DATA "data"
#define L2DE_TILEDMAP_ATTR_ENCODING "encoding"

// Property
#define L2DE_TILEDMAP_NODE_PROPERTIES "properties"
#define L2DE_TILEDMAP_NODE_PROPERTY "property"
#define L2DE_TILEDMAP_ATTR_TYPE "type"
#define L2DE_TILEDMAP_ATTR_VALUE "value"
#define L2DE_TILEDMAP_PROPERTY_TYPE_BOOL "bool"
#define L2DE_TILEDMAP_PROPERTY_TYPE_COLOR "color"
#define L2DE_TILEDMAP_PROPERTY_TYPE_FILE "file"
#define L2DE_TILEDMAP_PROPERTY_TYPE_FLOAT "float"
#define L2DE_TILEDMAP_PROPERTY_TYPE_INT "int"
#define L2DE_TILEDMAP_PROPERTY_TYPE_STRING "string"
#define L2DE_TILEDMAP_PROPERTY_TYPE_OBJECT "object"

// Tile
#define L2DE_TILEDMAP_NODE_TILE "tile"
#define L2DE_TILEDMAP_ATTR_ID "id"

// Smart Property
#define L2DE_TILEDMAP_SMART_LOADBACKGROUND "LoadBackground"
#define L2DE_TILEDMAP_SMART_LAYER "Layer"
